name: Build and Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  result_build:
    name: Build Every Application and Push to DockerHub with Version Tags.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: DockerHub Login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Result Docker Image With Version
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/result:${{ env.RELEASE_VERSION }} ./result
      - name: Push Result to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/result:${{ env.RELEASE_VERSION }}
      - name: Build Vote Docker Image With Version
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vote:${{ env.RELEASE_VERSION }} ./vote
      - name: Push Vote to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote:${{ env.RELEASE_VERSION }}
      - name: Build Worker Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker:${{ env.RELEASE_VERSION }} ./worker
      - name: Push Worker to Docker Hub With Version
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:${{ env.RELEASE_VERSION }}
     
      - name: Run Integration Tests with CodeceptJS
        run: |
          cd integration/ && npm install && npm run codeceptjs
