# This is a basic workflow to help you get started with Actions

name: MainFlow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code_quality:
    name: Check code quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check code quality
        uses: codeinspectorio/github-action@master
        with:
          repo_token: ${{ secrets.GIT_TOKEN }}
          code_inspector_access_key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
          code_inspector_secret_key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
          min_quality_grade: 'WARNING'
          min_quality_score: '0'
          max_complex_functions_rate: '0.1'
          max_long_functions_rate: '0.1'
          max_defects_rate: '0.1'
          max_violations_rate: '0.1'
  
      
  docker_build_and_push:
    name: Docker build and push
    runs-on: ubuntu-latest
    needs: [code_quality]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: DockerHub Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build Docker Images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/result ./result
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vote ./vote
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker ./worker
      
      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/result
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker
     
